// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSupabaseConfigStatus, getSupabasePublicEnv } from '@/lib/supabase-config';
import { PREVIEW_LABS, PREVIEW_DOCTORS } from '../../lib/demo-listings';

function createSupabaseClient() {
  const { url, key } = getSupabasePublicEnv();
  const status = getSupabaseConfigStatus();

  if (!url || !key) {
    throw new Error(
      'Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY in Healthsurya/.env.',
    );
  }

  if (!status.configured) {
    throw new Error(status.reason ?? 'Supabase URL is not configured.');
  }

  return createClient<Database>(url, key, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
    },
  });
}

// Client-side mock state attached to window
const getMockDbState = () => {
  if (typeof window === "undefined") {
    return {
      profiles: [],
      bookings: [],
      doctor_appointments: [],
      labs: PREVIEW_LABS,
      lab_tests: [],
      tests: [],
      doctors: PREVIEW_DOCTORS,
      reviews: [],
    };
  }
  const w = window as any;
  if (!w.mockDbState) {
    w.mockDbState = {
      profiles: [
        {
          id: "b1000001-0001-4000-8000-000000000001",
          clerk_user_id: "b1000001-0001-4000-8000-000000000001",
          phone: "9876500505",
          email: "patient@healthsurya.com",
          full_name: "Rahul Sharma",
          role: "patient",
          wallet_balance: 10000,
          verification_status: "approved",
          is_active: true,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        }
      ],
      bookings: [
        {
          id: "bk-mock-001",
          patient_id: "b1000001-0001-4000-8000-000000000001",
          lab_id: "b1000001-0001-4000-8000-000000000001",
          test_id: "e1000001-0001-4000-8000-000000000001",
          scheduled_at: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
          status: "pending",
          home_collection: true,
          address: "123, Civil Lines, Jaunpur",
          notes: "Patient requires morning test.",
          price: 499,
          payment_status: "pending",
          referred_doctor_id: null,
          referred_doctor_name: null,
          prescription_verified: false,
          commission_amount: 0,
          report_url: null,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        }
      ],
      doctor_appointments: [],
      labs: PREVIEW_LABS.map(l => ({
        ...l,
        owner_id: "d1000001-0001-4000-8000-000000000001",
        phone: "9876500000",
        email: "preview.lab@healthsurya.com",
        open_time: "07:00",
        close_time: "21:00",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })),
      doctors: PREVIEW_DOCTORS.map(d => ({
        ...d,
        owner_id: "c1000001-0001-4000-8000-000000000001",
        qualification: "MBBS, MD",
        experience_years: d.experience_years ?? 10,
        consultation_fee: d.consultation_fee ?? 500,
        clinic_name: d.clinic_name ?? `${d.full_name} Clinic`,
        clinic_address: d.clinic_address ?? "Civil Lines",
        clinic_phone: "9000000000",
        whatsapp: d.whatsapp ?? "9000000000",
        services: d.services ?? ["Consultation", "Follow-up"],
        open_time: d.open_time ?? "09:00",
        close_time: d.close_time ?? "20:00",
        published: true,
        verified: true,
        profile_views: d.profile_views ?? 120,
        whatsapp_clicks: d.whatsapp_clicks ?? 45,
        total_reviews: d.total_reviews ?? 28,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })),
      lab_tests: PREVIEW_LABS.flatMap(l => ([
        {
          id: `t1-${l.id.slice(3)}`,
          lab_id: l.id,
          test_id: "e1000001-0001-4000-8000-000000000001",
          price: l.minPrice || 299,
          home_collection: true,
          available: true,
          turnaround_hours: 24,
          tests: { name: "Complete Blood Count (CBC)", category: "Pathology" }
        },
        {
          id: `t2-${l.id.slice(3)}`,
          lab_id: l.id,
          test_id: "e1000002-0001-4000-8000-000000000002",
          price: (l.minPrice || 299) + 100,
          home_collection: true,
          available: true,
          turnaround_hours: 24,
          tests: { name: "Thyroid Profile (T3, T4, TSH)", category: "Hormone" }
        }
      ])),
      tests: [
        { id: "e1000001-0001-4000-8000-000000000001", name: "Complete Blood Count (CBC)", category: "Pathology" },
        { id: "e1000002-0001-4000-8000-000000000002", name: "Thyroid Profile (T3, T4, TSH)", category: "Hormone" }
      ],
      reviews: [],
      doctor_gallery: [],
      doctor_reviews: [],
      user_roles: [
        { id: "r1", user_id: "f1000001-0001-4000-8000-000000000001", role: "admin" },
        { id: "r2", user_id: "c1000001-0001-4000-8000-000000000001", role: "doctor" },
        { id: "r3", user_id: "d1000001-0001-4000-8000-000000000001", role: "lab" },
        { id: "r4", user_id: "d1000002-0001-4000-8000-000000000002", role: "pharmacy" },
        { id: "r5", user_id: "b1000001-0001-4000-8000-000000000001", role: "patient" }
      ],
      medicine_orders: [],
      order_tracking_events: [],
      doctor_profiles: [],
      lab_profiles: [],
      pharmacy_profiles: [],
      kyc_documents: [],
      verification_requests: [],
      tickets: [],
      ticket_messages: [],
      ai_conversations: [],
      profile_completion: [],
      trust_scores: [],
      notifications: [],
      audit_logs: [],
      lab_branding: [],
      verification_logs: []
    };
  }
  return w.mockDbState;
};

// Client-side query filter executor
function executeClientMockQuery(state: any) {
  const db = getMockDbState();
  let list = db[state.tableName] || [];

  // Filter eq
  for (const [col, val] of Object.entries(state.eqFilters)) {
    list = list.filter((item: any) => item[col] === val);
  }

  // Filter in
  if (state.inFilters) {
    for (const [col, vals] of Object.entries(state.inFilters)) {
      if (Array.isArray(vals)) {
        list = list.filter((item: any) => vals.includes(item[col]));
      }
    }
  }

  // Filter ilike
  if (state.ilikeFilters) {
    for (const [col, val] of Object.entries(state.ilikeFilters)) {
      const searchVal = String(val).replace(/%/g, "").toLowerCase();
      list = list.filter((item: any) => item[col] && String(item[col]).toLowerCase().includes(searchVal));
    }
  }

  // Filter or
  if (state.orFilterStr) {
    const filters = state.orFilterStr.split(",");
    list = list.filter((item: any) => {
      return filters.some((f: string) => {
        const match = f.match(/(\w+)\.ilike\.%([^%]+)%/);
        if (match) {
          const col = match[1];
          const query = match[2].toLowerCase();
          return item[col] && String(item[col]).toLowerCase().includes(query);
        }
        return false;
      });
    });
  }

  // Order
  if (state.orderCol) {
    list = [...list].sort((a: any, b: any) => {
      const aVal = a[state.orderCol];
      const bVal = b[state.orderCol];
      if (aVal === bVal) return 0;
      const factor = state.orderAsc ? 1 : -1;
      return aVal > bVal ? factor : -factor;
    });
  }

  // Limit
  if (state.limitVal > 0) {
    list = list.slice(0, state.limitVal);
  }

  // Join logic
  if (state.tableName === "bookings") {
    const getCookie = (name: string) => {
      if (typeof window === "undefined") return null;
      const value = `; ${document.cookie}`;
      const parts = value.split(`; ${name}=`);
      if (parts.length === 2) return parts.pop()?.split(';').shift();
      return null;
    };
    const mockRole = getCookie("mock_role") || "patient";
    const isInternalRole = ["doctor", "lab", "admin", "super_admin"].includes(mockRole);

    list = list.map((b: any) => {
      const lab = db.labs.find((l: any) => l.id === b.lab_id);
      const test = db.tests.find((t: any) => t.id === b.test_id);
      const bookingData = {
        ...b,
        labs: lab ? { name: lab.name, city: lab.city, address: lab.address, image_url: lab.image_url } : null,
        tests: test ? { name: test.name } : null
      };
      
      if (!isInternalRole) {
        delete bookingData.commission_amount;
        delete bookingData.referred_doctor_id;
        delete bookingData.referred_doctor_name;
        delete bookingData.prescription_verified;
      }
      return bookingData;
    });
  } else if (state.tableName === "lab_tests") {
    list = list.map((lt: any) => {
      const test = db.tests.find((t: any) => t.id === lt.test_id);
      return {
        ...lt,
        tests: test ? { name: test.name, category: test.category } : null
      };
    });
  }

  if (state.isSingle) {
    return { data: list[0] || null, error: list[0] ? null : { message: "Row not found" }, count: list.length };
  }
  if (state.isMaybeSingle) {
    return { data: list[0] || null, error: null, count: list.length };
  }

  return { data: list, error: null, count: list.length };
}

function createClientMockQueryBuilder(tableName: string) {
  const state = {
    tableName,
    eqFilters: {} as Record<string, any>,
    inFilters: {} as Record<string, any[]>,
    ilikeFilters: {} as Record<string, string>,
    orFilterStr: "",
    selectFields: "*",
    isSingle: false,
    isMaybeSingle: false,
    orderCol: "",
    orderAsc: false,
    limitVal: 0,
  };

  const builder = {
    select(fields = "*", options?: any) {
      state.selectFields = fields;
      return builder;
    },
    eq(col: string, val: any) {
      state.eqFilters[col] = val;
      return builder;
    },
    in(col: string, values: any[]) {
      state.inFilters[col] = values;
      return builder;
    },
    ilike(col: string, val: string) {
      state.ilikeFilters[col] = val;
      return builder;
    },
    or(filterStr: string) {
      state.orFilterStr = filterStr;
      return builder;
    },
    order(col: string, opts?: { ascending?: boolean }) {
      state.orderCol = col;
      state.orderAsc = opts?.ascending ?? false;
      return builder;
    },
    limit(val: number) {
      state.limitVal = val;
      return builder;
    },
    single() {
      state.isSingle = true;
      return Promise.resolve(executeClientMockQuery(state));
    },
    maybeSingle() {
      state.isMaybeSingle = true;
      return Promise.resolve(executeClientMockQuery(state));
    },
    insert(payload: any) {
      const items = Array.isArray(payload) ? payload : [payload];
      const inserted: any[] = [];
      const db = getMockDbState();
      for (const item of items) {
        const row = {
          id: item.id || `mock-id-${Math.random().toString(36).substring(2, 11)}`,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
          ...item
        };
        db[tableName].push(row);
        inserted.push(row);
      }
      const resVal = Array.isArray(payload) ? inserted : inserted[0];
      return {
        select() {
          return {
            single() {
              return Promise.resolve({ data: resVal, error: null });
            },
            then(onfulfilled: any) {
              return Promise.resolve({ data: inserted, error: null }).then(onfulfilled);
            }
          };
        },
        then(onfulfilled?: (value: any) => any) {
          return Promise.resolve({ data: resVal, error: null }).then(onfulfilled);
        }
      } as any;
    },
    update(payload: any) {
      const updateBuilder = {
        eq(col: string, val: any) {
          state.eqFilters[col] = val;
          return updateBuilder;
        },
        then(onfulfilled?: (value: any) => any, onrejected?: (reason: any) => any) {
          const db = getMockDbState();
          const list = db[tableName] || [];
          for (const item of list) {
            let match = true;
            for (const [fCol, fVal] of Object.entries(state.eqFilters)) {
              if (item[fCol] !== fVal) match = false;
            }
            if (match) {
              Object.assign(item, payload, { updated_at: new Date().toISOString() });
            }
          }
          return Promise.resolve({ data: {}, error: null }).then(onfulfilled, onrejected);
        }
      };
      return updateBuilder;
    },
    delete() {
      return {
        eq(col: string, val: any) {
          state.eqFilters[col] = val;
          const db = getMockDbState();
          const list = db[tableName] || [];
          const remaining = list.filter((item: any) => item[col] !== val);
          db[tableName] = remaining;
          return Promise.resolve({ data: {}, error: null });
        }
      };
    },
    then(onfulfilled?: (value: any) => any, onrejected?: (reason: any) => any) {
      return Promise.resolve(executeClientMockQuery(state)).then(onfulfilled, onrejected);
    }
  };

  return builder;
}

let _supabase: ReturnType<typeof createSupabaseClient> | null | undefined;

function getSupabaseClient() {
  if (_supabase !== undefined) return _supabase;
  const { url, key } = getSupabasePublicEnv();
  if (!url || !key) {
    _supabase = null;
    return null;
  }
  try {
    _supabase = createSupabaseClient();
  } catch {
    _supabase = null;
  }
  return _supabase;
}

function getCookie(name: string) {
  if (typeof window === "undefined") return null;
  const value = `; ${document.cookie}`;
  const parts = value.split(`; ${name}=`);
  if (parts.length === 2) return parts.pop()?.split(';').shift();
  return null;
}

function createClientBypassQueryBuilder(tableName: string) {
  const state = {
    tableName,
    selectFields: "*",
    eqFilters: {} as Record<string, any>,
    inFilters: {} as Record<string, any[]>,
    ilikeFilters: {} as Record<string, string>,
    orFilterStr: "",
    orderCol: "",
    orderAsc: false,
    limitVal: 0,
    isSingle: false,
    isMaybeSingle: false,
    action: "select",
    payload: null as any,
  };

  const executeBypassQuery = async () => {
    try {
      const res = await fetch("/api/tester/db-query", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(state),
      });
      if (!res.ok) {
        const errData = await res.json();
        return { data: null, error: { message: errData.error || "Bypass query failed" } };
      }
      return await res.json();
    } catch (err: any) {
      return { data: null, error: { message: err.message } };
    }
  };

  const builder: any = {
    select(fields = "*") {
      state.selectFields = fields;
      return builder;
    },
    eq(col: string, val: any) {
      state.eqFilters[col] = val;
      return builder;
    },
    in(col: string, values: any[]) {
      state.inFilters[col] = values;
      return builder;
    },
    ilike(col: string, val: string) {
      state.ilikeFilters[col] = val;
      return builder;
    },
    or(filterStr: string) {
      state.orFilterStr = filterStr;
      return builder;
    },
    order(col: string, opts?: { ascending?: boolean }) {
      state.orderCol = col;
      state.orderAsc = opts?.ascending ?? false;
      return builder;
    },
    limit(val: number) {
      state.limitVal = val;
      return builder;
    },
    single() {
      state.isSingle = true;
      return executeBypassQuery();
    },
    maybeSingle() {
      state.isMaybeSingle = true;
      return executeBypassQuery();
    },
    insert(payload: any) {
      state.action = "insert";
      state.payload = payload;
      return {
        select() {
          return {
            single() {
              state.isSingle = true;
              return executeBypassQuery();
            },
            then(onfulfilled: any) {
              return executeBypassQuery().then(onfulfilled);
            }
          };
        },
        then(onfulfilled?: (value: any) => any) {
          return executeBypassQuery().then(onfulfilled);
        }
      } as any;
    },
    update(payload: any) {
      state.action = "update";
      state.payload = payload;
      const updateBuilder = {
        eq(col: string, val: any) {
          state.eqFilters[col] = val;
          return updateBuilder;
        },
        then(onfulfilled?: (value: any) => any, onrejected?: (reason: any) => any) {
          return executeBypassQuery().then(onfulfilled, onrejected);
        }
      };
      return updateBuilder;
    },
    delete() {
      state.action = "delete";
      return {
        eq(col: string, val: any) {
          state.eqFilters[col] = val;
          return executeBypassQuery();
        }
      };
    },
    then(onfulfilled?: (value: any) => any, onrejected?: (reason: any) => any) {
      return executeBypassQuery().then(onfulfilled, onrejected);
    }
  };

  return builder;
}

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    const hasTesterKey = typeof window !== "undefined" && !!getCookie("tester_key");
    const hasMockRole = typeof window !== "undefined" && (!!getCookie("mock_role") || !!getCookie("sb_session"));
    const isBypassActive = hasTesterKey && hasMockRole;

    if (process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY === "pk_test_Y2xlcmsubW9jay5kZXYk" || hasTesterKey) {
      if (prop === "from") {
        return (tableName: string) => {
          if (isBypassActive) {
            return createClientBypassQueryBuilder(tableName);
          } else {
            return createClientMockQueryBuilder(tableName);
          }
        };
      }
      if (prop === "auth") {
        return {
          async getSession() {
            const mockRole = getCookie("mock_role") || getCookie("sb_session");
            if (!mockRole) return { data: { session: null }, error: null };
            
            const userId = mockRole === "admin" ? "f1000001-0001-4000-8000-000000000001" :
                           mockRole === "doctor" ? "c1000001-0001-4000-8000-000000000001" :
                           mockRole === "lab" ? "d1000001-0001-4000-8000-000000000001" :
                           mockRole === "pharmacy" ? "d1000002-0001-4000-8000-000000000002" :
                           "b1000001-0001-4000-8000-000000000001";
            return {
              data: {
                session: {
                  user: {
                    id: userId,
                    email: `${mockRole}@healthsurya.com`,
                    user_metadata: { full_name: `Test ${mockRole.charAt(0).toUpperCase() + mockRole.slice(1)}` },
                  },
                },
              },
              error: null,
            };
          },
          async getUser() {
            const res = await this.getSession();
            return { data: { user: res.data.session?.user ?? null }, error: null };
          },
          async signInWithOtp({ email, phone, options }: any) {
            let role = options?.data?.role || getCookie("mock_role") || getCookie("mock_temp_role");
            if (!role) {
              role = "patient";
              const identifier = email || phone || "";
              const clean = identifier.toLowerCase();
              if (clean.includes("doctor") || clean.includes("dr.") || clean.includes("dr_") || clean.startsWith("dr@")) role = "doctor";
              else if (clean.includes("lab")) role = "lab";
              else if (clean.includes("pharmacy")) role = "pharmacy";
              else if (clean.includes("admin")) role = "admin";
            }
            
            if (typeof window !== "undefined") {
              document.cookie = `mock_temp_role=${role}; path=/`;
              document.cookie = `mock_temp_dest=${email || phone || ""}; path=/`;
            }
            return { data: {}, error: null };
          },
          async verifyOtp({ email, phone, token, type }: any) {
            const tempRole = getCookie("mock_temp_role") || "patient";
            const tempDest = getCookie("mock_temp_dest") || "";
            if (typeof window !== "undefined") {
              document.cookie = `mock_role=${tempRole}; path=/`;
              document.cookie = `sb_session=${tempRole}; path=/`;
            }
            
            const isSeededEmail = tempDest === "admin@healthsurya.com" ||
                                  tempDest === "doctor@healthsurya.com" ||
                                  tempDest === "lab@healthsurya.com" ||
                                  tempDest === "pharmacy@healthsurya.com" ||
                                  tempDest === "patient@healthsurya.com";
            
            const uuidv4 = () => 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
              const r = Math.random() * 16 | 0;
              return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16);
            });

            const userId = isSeededEmail ? (
              tempRole === "admin" ? "f1000001-0001-4000-8000-000000000001" :
              tempRole === "doctor" ? "c1000001-0001-4000-8000-000000000001" :
              tempRole === "lab" ? "d1000001-0001-4000-8000-000000000001" :
              tempRole === "pharmacy" ? "d1000002-0001-4000-8000-000000000002" :
              "b1000001-0001-4000-8000-000000000001"
            ) : uuidv4();

            return {
              data: {
                user: {
                  id: userId,
                  email: tempDest || `${tempRole}@healthsurya.com`,
                  user_metadata: { full_name: `Test ${tempRole.charAt(0).toUpperCase() + tempRole.slice(1)}` },
                },
                session: {
                  user: {
                    id: userId,
                    email: tempDest || `${tempRole}@healthsurya.com`,
                  }
                }
              },
              error: null
            };
          },
          async signOut() {
            if (typeof window !== "undefined") {
              document.cookie = "mock_role=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT";
              document.cookie = "sb_session=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT";
              document.cookie = "tester_key=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT";
            }
            window.location.href = "/";
            return { error: null };
          },
          onAuthStateChange(callback: any) {
            return {
              data: {
                subscription: {
                  unsubscribe() {}
                }
              }
            };
          }
        };
      }
    }
    const client = getSupabaseClient();
    if (!client) {
      const status = getSupabaseConfigStatus();
      throw new Error(status.reason ?? 'Supabase is not configured.');
    }
    return Reflect.get(client, prop, receiver);
  },
});

export { getSupabaseClient };
